name: quality

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  format:
    name: Format
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
      - name: Format
        run: nix develop .#ci --command just format
  lint:
    name: Lint
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: nix develop .#ci --command just lint
  build:
    name: Build
    runs-on: nix
    needs: [format, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: nix develop .#ci --command just build
